leftnav:
- identifier: 1fd51221-c39e-bc7a-825d-fbd7bd5d28f8
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 13c3f8b4-e335-c764-6b82-888fe28512b4
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: a5e80546-b3ae-7ac2-4ca7-b41014b2e688
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 9df4f259-0fde-275a-9ffc-fdb7c61de743
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
